apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  # ! NodePort, ClusterIP, LoadBalancer
  type: NodePort
  ports:
    # ! Port of the POD
    - targetPort: 80 
      # ! Port of the Service
      # ! think of the service as internal server
      # ! This is the only required for NodePort
      port: 80 
      # ! Port of the Node; valid range 30000 - 32767
      # ! This is not needed for ClusterIP and LoadBalancer options
      nodePort: 30008
  # ! this section is to link the service to a POD
  selector:
    app: myapp
    type: frontend