apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-dpeloyment
  labels:
    tier: frontend
    app: nginx
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: myapp # ! These two need to match
  template:
    metadata:
      name: nginx-2
      labels:
        app: myapp # ! These two need to match
    spec:
      containers:
        - name: nginx
          image: nginx