apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
  containers:
    - name: ubuntu-sleeper
      image: ubuntu-sleeper
      command: ["sleep"] # overrides the default ENTRYPOINT
      args: ["3600"]     # overrides the default CMD
      env:
        - name: APP_COLOR
          value: pink
        - name: APP_MODE
          value: test
      envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret